### ISSUE TITLE
GetVersion() API has been deprecated and should be replaced with GetOsVersion()

### ISSUE THREAD

**Issue by chrisdp** [Swrve/swrve-roku-sdk#2]
The SDK is using deprecated APIs (as of 9.2) and throws warning from Rokus Static Analysis:

![image](https://user-images.githubusercontent.com/9591618/138357305-bc3d74e8-9df8-47ff-b697-b9864aa73a73.png)

![image](https://user-images.githubusercontent.com/9591618/138357356-25494782-d922-44a9-af96-eae22475024d.png)

**Comment by KevBrodigan** [comment]
@chrisdp Thanks Chris we will look to update to the new API soon and likely bump min support to 9.2.  I'm assuming it's not really necessary to try support older versions with a firmware check in the code to use the older API for < 9.2?  Is this warning actually preventing channel update for you?

**Comment by chrisdp** [comment]
It is not preventing us but this is flagged by Roku on every application submission.

**Comment by KevBrodigan** [comment]
Updated deprecated API in latest release
